version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  skip-dirs:
    - plugin

issues:
  uniq-by-line: false

linters:
  default: none
  enable:
    - loglint

  settings:
    custom:
      loglint:
        type: "module"
        description: "Checks Go log messages for style, language and sensitive data"
        settings: {}

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true