version: '3'

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.25'
  GOLANGCI_LINT_VERSION: 'v2.1.5'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'

tasks:
  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.
      
      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  build-custom-gcl:
    desc: "Собирает кастомный golangci-lint с плагином loglint"
    summary: |
      Собирает кастомный бинарник golangci-lint (custom-gcl) с подключённым
      модульным плагином loglint из текущего модуля.
    deps: [ install-golangci-lint ]
    cmds:
      - |
        echo "Собираем custom-gcl с модульным плагином loglint..."
        {{.GOLANGCI_LINT}} custom -v

  lint:
    desc: "Запускает кастомный golangci-lint (custom-gcl) для проекта"
    summary: |
      Запускает кастомный бинарник golangci-lint (custom-gcl), собранный с
      модульным плагином loglint. Линтер проверяет код на соответствие
      соглашениям по логированию и общим лучшим практикам.
      
      Зависимости:
        - build-custom-gcl: собирает кастомный golangci-lint с плагином loglint
    deps: [ build-custom-gcl ]
    cmds:
      - |
        echo "Запускаем кастомный golangci-lint (custom-gcl) ..."
        ./bin/custom-gcl run ./... --config=.golangci.yml